const fishNamesByLocation = {
  poland_small_lake: [
    "Karp",
    "Karp lustrzeń",
    "Leszcz",
    "Płoć",
    "Szczupak",
    "Okoń",
    "Lin",
    "Karaś",
    "Węgorz",
    "Sandacz",
    "Amur",
    "Sum",
    "Jaź",
    "Kleń",
    "Ukleja",
  ],
  usa_river_delta: [
    "Largemouth Bass",
    "Smallmouth Bass",
    "Catfish",
    "Bluegill",
    "Crappie",
    "Pike",
    "Gar",
    "Bowfin",
    "Drum",
    "Perch",
    "Sunfish",
    "Shad",
    "Sturgeon",
    "Carp",
    "Walleye",
  ],
  canada_deep_lake: [
    "Lake Trout",
    "Northern Pike",
    "Walleye",
    "Salmon",
    "Whitefish",
    "Perch",
    "Cisco",
    "Burbot",
    "Grayling",
    "Muskie",
    "Bass",
    "Sucker",
    "Chub",
    "Smelt",
    "Arctic Char",
  ],
  norway_ocean_coast: [
    "Cod",
    "Mackerel",
    "Halibut",
    "Herring",
    "Pollock",
    "Haddock",
    "Ling",
    "Saithe",
    "Redfish",
    "Flatfish",
    "Shark (rare)",
    "Tuna",
    "Salmon",
    "Eel",
    "Ray",
  ],
  japan_mountain_river: [
    "Ayu",
    "Trout",
    "Carp",
    "Catfish",
    "Salmon",
    "Eel",
    "Bass",
    "Sweetfish",
    "Goby",
    "Loach",
    "Minnow",
    "Perch",
    "Pike",
    "Char",
    "Crucian Carp",
  ],
  brazil_amazon_river: [
    "Piranha",
    "Arapaima",
    "Peacock Bass",
    "Catfish",
    "Electric Eel",
    "Pacu",
    "Arowana",
    "Tambaqui",
    "Stingray",
    "Knife Fish",
    "Oscar",
    "Dorado",
    "Snakehead",
    "Tiger Fish",
    "Payara",
  ],
  australia_coral_sea: [
    "Tuna",
    "Barracuda",
    "Grouper",
    "Snapper",
    "Shark (rare)",
    "Mahi Mahi",
    "Trevally",
    "Coral Trout",
    "Emperor Fish",
    "Wrasse",
    "Parrotfish",
    "Surgeonfish",
    "Triggerfish",
    "Lionfish",
    "Eel",
  ],
  egypt_nile_river: [
    "Nile Perch",
    "Tilapia",
    "Catfish",
    "Tigerfish",
    "Carp",
    "Eel",
    "Bichir",
    "Lungfish",
    "Barbel",
    "Shad",
    "Mullet",
    "Bass",
    "Perch",
    "Snakehead",
    "Gar",
  ],
  france_carp_lake: [
    "Big Carp",
    "Mirror Carp",
    "Tench",
    "Bream",
    "Roach",
    "Pike",
    "Perch",
    "Zander",
    "Catfish",
    "Crucian Carp",
    "Chub",
    "Barbel",
    "Rudd",
    "Bleak",
    "Eel",
  ],
  iceland_ice_river: [
    "Arctic Char",
    "Salmon",
    "Trout",
    "Grayling",
    "Whitefish",
    "Pike",
    "Perch",
    "Charr",
    "Cod (rare)",
    "Haddock (rare)",
    "Eel",
    "Sculpin",
    "Smelt",
    "Stickleback",
    "Flounder",
  ],
};

const fishGuideOverrides = {
  poland_small_lake: {
    Karp: { best: ["kukurydza", "chleb"], ok: ["robak"], bad: ["sztuczne"] },
    "Karp lustrzeń": { best: ["kukurydza"], ok: ["chleb"], bad: ["spinning"] },
    Leszcz: { best: ["robak"], ok: ["kukurydza"], bad: ["sztuczne"] },
    Płoć: { best: ["robak"], ok: ["chleb"], bad: ["spinning"] },
    Szczupak: { best: ["wobler", "guma"], ok: ["spinner"], bad: ["kukurydza"] },
    Okoń: { best: ["guma", "robak"], ok: ["spinner"], bad: ["chleb"] },
    Lin: { best: ["robak"], ok: ["kukurydza"], bad: ["sztuczne"] },
    Karaś: { best: ["chleb"], ok: ["robak"], bad: ["spinning"] },
    Węgorz: { best: ["robak", "mała ryba"], ok: ["noc"], bad: ["sztuczne"] },
    Sandacz: { best: ["guma"], ok: ["wobler"], bad: ["kukurydza"] },
    Amur: { best: ["kukurydza"], ok: ["roślinne"], bad: ["spinning"] },
    Sum: { best: ["mała ryba"], ok: ["robak"], bad: ["chleb"] },
    Jaź: { best: ["robak"], ok: ["chleb"], bad: ["heavy spinning"] },
    Kleń: { best: ["robak"], ok: ["małe sztuczne"], bad: ["kukurydza"] },
    Ukleja: { best: ["robak"], ok: ["lekki zestaw"], bad: ["wszystko ciężkie"] },
  },
  usa_river_delta: {
    "Largemouth Bass": { best: ["wobler", "guma"], ok: ["spinner"], bad: ["kukurydza"] },
    "Smallmouth Bass": { best: ["guma"], ok: ["wobler"], bad: ["chleb"] },
    Catfish: { best: ["robak", "mięso"], ok: ["mała ryba"], bad: ["szybki spinning"] },
    Bluegill: { best: ["robak"], ok: ["małe przynęty"], bad: ["duże przynęty"] },
    Crappie: { best: ["małe przynęty"], ok: ["robak"], bad: ["ciężkie przynęty"] },
    Pike: { best: ["wobler"], ok: ["spinner"], bad: ["kukurydza"] },
    Gar: { best: ["duże przynęty"], ok: ["mała ryba"], bad: ["chleb"] },
    Bowfin: { best: ["guma"], ok: ["mięso"], bad: ["kukurydza"] },
    Drum: { best: ["robak"], ok: ["naturalne"], bad: ["popper"] },
    Perch: { best: ["robak"], ok: ["guma"], bad: ["duże przynęty"] },
    Sunfish: { best: ["robak"], ok: ["chleb"], bad: ["ciężkie przynęty"] },
    Shad: { best: ["plankton style"], ok: ["małe przynęty"], bad: ["duże przynęty"] },
    Sturgeon: { best: ["ciężkie przynęty"], ok: ["mięso"], bad: ["surface bait"] },
    Carp: { best: ["kukurydza"], ok: ["chleb"], bad: ["wobler"] },
    Walleye: { best: ["guma"], ok: ["wobler"], bad: ["kukurydza"] },
  },
  canada_deep_lake: {
    "Lake Trout": { best: ["robak", "małe wobblery"], ok: ["wolne prowadzenie"], bad: ["szybki popper"] },
    "Northern Pike": { best: ["duże wobblery"], ok: ["mała ryba"], bad: ["kukurydza"] },
    Salmon: { best: ["sztuczne", "szybkie prowadzenie"], ok: ["wobler"], bad: ["stojący chleb"] },
    Walleye: { best: ["guma", "noc"], ok: ["wolny wobler"], bad: ["powierzchniowe"] },
    Whitefish: { best: ["naturalne"], ok: ["robak"], bad: ["duże przynęty"] },
  },
  norway_ocean_coast: {
    Cod: { best: ["robak", "mięso"], ok: ["ciężkie przynęty"], bad: ["surface bait"] },
    Mackerel: { best: ["szybkie przynęty"], ok: ["spinner"], bad: ["stojący chleb"] },
    Halibut: { best: ["duże przynęty"], ok: ["mięso"], bad: ["mały robak"] },
    Herring: { best: ["małe przynęty"], ok: ["szybkie prowadzenie"], bad: ["ciężkie przynęty"] },
    "Shark (rare)": { best: ["duża przynęta", "rzadkie"], ok: ["mięso"], bad: ["chleb"] },
  },
  japan_mountain_river: {
    Trout: { best: ["robak"], ok: ["mały wobler"], bad: ["ciężkie przynęty"] },
    Ayu: { best: ["naturalne"], ok: ["lekki zestaw"], bad: ["głośne przynęty"] },
    Bass: { best: ["guma"], ok: ["wobler"], bad: ["kukurydza"] },
    Catfish: { best: ["robak"], ok: ["mięso"], bad: ["spinner"] },
    Salmon: { best: ["sztuczne"], ok: ["szybkie prowadzenie"], bad: ["chleb"] },
  },
  brazil_amazon_river: {
    Piranha: { best: ["mięso"], ok: ["robak"], bad: ["roślinne"] },
    Arapaima: { best: ["duża ryba", "bait fish"], ok: ["duży wobler"], bad: ["mały robak"] },
    "Peacock Bass": { best: ["wobler"], ok: ["guma"], bad: ["kukurydza"] },
    "Electric Eel": { best: ["robak"], ok: ["mała ryba"], bad: ["popper"] },
    Arowana: { best: ["surface bait"], ok: ["mały wobler"], bad: ["ciężki jig"] },
  },
  australia_coral_sea: {
    Tuna: { best: ["szybkie przynęty"], ok: ["wobler"], bad: ["robak"] },
    Barracuda: { best: ["wobler"], ok: ["szybkie przynęty"], bad: ["kukurydza"] },
    "Shark (rare)": { best: ["duże przynęty"], ok: ["mięso"], bad: ["chleb"] },
    Snapper: { best: ["robak"], ok: ["mięso"], bad: ["surface bait"] },
    Grouper: { best: ["mięso"], ok: ["duże przynęty"], bad: ["małe przynęty"] },
  },
  egypt_nile_river: {
    "Nile Perch": { best: ["guma"], ok: ["wobler"], bad: ["kukurydza"] },
    Tilapia: { best: ["roślinne"], ok: ["chleb"], bad: ["duże przynęty"] },
    Catfish: { best: ["robak"], ok: ["mięso"], bad: ["spinner"] },
    Tigerfish: { best: ["szybkie przynęty"], ok: ["wobler"], bad: ["kukurydza"] },
  },
  france_carp_lake: {
    "Big Carp": { best: ["kukurydza"], ok: ["chleb"], bad: ["spinning"] },
    "Mirror Carp": { best: ["kukurydza"], ok: ["chleb"], bad: ["spinning"] },
    Tench: { best: ["robak"], ok: ["kukurydza"], bad: ["sztuczne"] },
    Bream: { best: ["robak"], ok: ["kukurydza"], bad: ["wobler"] },
    Pike: { best: ["wobler"], ok: ["spinner"], bad: ["kukurydza"] },
  },
  iceland_ice_river: {
    Salmon: { best: ["sztuczne"], ok: ["szybkie prowadzenie"], bad: ["chleb"] },
    Trout: { best: ["robak"], ok: ["mały wobler"], bad: ["duże przynęty"] },
    "Arctic Char": { best: ["naturalne"], ok: ["robak"], bad: ["ciężkie przynęty"] },
    Charr: { best: ["naturalne"], ok: ["robak"], bad: ["ciężkie przynęty"] },
  },
};

const locationGuideNotes = {
  canada_deep_lake: "Zimna woda oznacza wolniejsze prowadzenie i dłuższe pauzy.",
  norway_ocean_coast: "Na oceanie mocniej liczy się rozmiar przynęty i kontrola napięcia.",
  iceland_ice_river: "W lodowej wodzie lepiej działa spokojna, naturalna prezentacja.",
};

const lureGuideLabels = {
  natural: "naturalne / robak / chleb",
  spinner: "spinner",
  crankbait: "wobler",
  jig: "guma / jig",
  spoon: "szybkie lub ciężkie przynęty",
  popper: "surface bait",
  minnow: "mała ryba",
};

function lureTypesForGuideTerms(terms = []) {
  const text = terms.join(" ").toLowerCase();
  const types = [];
  if (/(kukurydza|chleb|robak|mięso|roślinne|naturalne|plankton|lekki zestaw|noc)/i.test(text)) types.push("natural");
  if (/(spinner|obrot)/i.test(text)) types.push("spinner");
  if (/(wobler|wobbl|crank)/i.test(text)) types.push("crankbait");
  if (/(guma|jig)/i.test(text)) types.push("jig");
  if (/(mała ryba|duża ryba|bait fish|rybka|minnow)/i.test(text)) types.push("minnow");
  if (/(szybkie|ciężkie|spoon|wahad)/i.test(text)) types.push("spoon");
  if (/(surface|powierzch|popper)/i.test(text)) types.push("popper");
  return [...new Set(types)];
}

const locationSeeds = [
  {
    id: "poland_small_lake",
    name: "Small Lake",
    country: "Polska",
    type: "Małe jezioro",
    difficulty: 1,
    unlockLevel: 1,
    travelCost: 0,
    requiredGear: "Starter 3 kg line, dowolna wędka",
    world: { x: 0.54, y: 0.31 },
    current: 0.04,
    depth: 0.42,
    palette: { water: "#285c64", shore: "#51673c" },
  },
  {
    id: "usa_river_delta",
    name: "River Delta",
    country: "USA",
    type: "Delta rzeczna",
    difficulty: 2,
    unlockLevel: 3,
    travelCost: 180,
    requiredGear: "Line 6 kg, reel 1.4x",
    world: { x: 0.2, y: 0.38 },
    current: 0.22,
    depth: 0.52,
    palette: { water: "#2f6568", shore: "#6f6a3f" },
  },
  {
    id: "canada_deep_lake",
    name: "Deep Lake",
    country: "Kanada",
    type: "Głębokie jezioro",
    difficulty: 3,
    unlockLevel: 5,
    travelCost: 320,
    requiredGear: "Line 8 kg, medium rod",
    world: { x: 0.22, y: 0.24 },
    current: 0.09,
    depth: 0.86,
    palette: { water: "#214f6f", shore: "#4f6250" },
  },
  {
    id: "norway_ocean_coast",
    name: "Ocean Coast",
    country: "Norwegia",
    type: "Morskie wybrzeże",
    difficulty: 5,
    unlockLevel: 8,
    travelCost: 580,
    requiredGear: "Line 14 kg, ocean reel",
    world: { x: 0.52, y: 0.21 },
    current: 0.34,
    depth: 0.92,
    palette: { water: "#163e58", shore: "#68736c" },
  },
  {
    id: "japan_mountain_river",
    name: "Mountain River",
    country: "Japonia",
    type: "Górska rzeka",
    difficulty: 4,
    unlockLevel: 7,
    travelCost: 520,
    requiredGear: "Control rod, light lures",
    world: { x: 0.82, y: 0.39 },
    current: 0.42,
    depth: 0.48,
    palette: { water: "#27666b", shore: "#586c3b" },
  },
  {
    id: "brazil_amazon_river",
    name: "Amazon River",
    country: "Brazylia",
    type: "Tropikalna rzeka",
    difficulty: 7,
    unlockLevel: 12,
    travelCost: 980,
    requiredGear: "Line 20 kg, high drag reel",
    world: { x: 0.36, y: 0.67 },
    current: 0.48,
    depth: 0.74,
    palette: { water: "#2a6757", shore: "#526f2f" },
  },
  {
    id: "australia_coral_sea",
    name: "Coral Sea",
    country: "Australia",
    type: "Rafa i otwarte morze",
    difficulty: 8,
    unlockLevel: 15,
    travelCost: 1280,
    requiredGear: "Line 25 kg, pro rod",
    world: { x: 0.82, y: 0.73 },
    current: 0.39,
    depth: 0.82,
    palette: { water: "#1f7780", shore: "#b17850" },
  },
  {
    id: "egypt_nile_river",
    name: "Nile River",
    country: "Egipt",
    type: "Duża ciepła rzeka",
    difficulty: 5,
    unlockLevel: 9,
    travelCost: 640,
    requiredGear: "Line 12 kg, drag 14",
    world: { x: 0.55, y: 0.47 },
    current: 0.3,
    depth: 0.62,
    palette: { water: "#2d6860", shore: "#9c7d45" },
  },
  {
    id: "france_carp_lake",
    name: "Carp Lake",
    country: "Francja",
    type: "Komercyjne jezioro karpiowe",
    difficulty: 4,
    unlockLevel: 6,
    travelCost: 420,
    requiredGear: "Line 10 kg, carp rod",
    world: { x: 0.5, y: 0.34 },
    current: 0.03,
    depth: 0.56,
    palette: { water: "#2f615f", shore: "#606b3d" },
  },
  {
    id: "iceland_ice_river",
    name: "Ice River",
    country: "Islandia",
    type: "Lodowa rzeka",
    difficulty: 6,
    unlockLevel: 10,
    travelCost: 760,
    requiredGear: "Line 14 kg, cold-water lures",
    world: { x: 0.46, y: 0.2 },
    current: 0.36,
    depth: 0.58,
    palette: { water: "#2d6e86", shore: "#8c9b9b" },
  },
];

const maxWeightOverrides = {
  Karp: 24,
  "Karp lustrzeń": 28,
  Leszcz: 7,
  Płoć: 1.8,
  Szczupak: 20,
  Okoń: 4,
  Lin: 7,
  Karaś: 3,
  Węgorz: 5,
  Sandacz: 15,
  Amur: 35,
  Sum: 90,
  Jaź: 4,
  Kleń: 6,
  Ukleja: 0.12,
  "Largemouth Bass": 9,
  "Smallmouth Bass": 6,
  Catfish: 60,
  Bluegill: 2,
  Crappie: 2.4,
  Pike: 22,
  Gar: 60,
  Bowfin: 10,
  Drum: 25,
  Perch: 4,
  Sunfish: 1,
  Shad: 3,
  Sturgeon: 150,
  Carp: 30,
  Walleye: 14,
  "Lake Trout": 35,
  "Northern Pike": 25,
  Salmon: 35,
  Whitefish: 5,
  Cisco: 2,
  Burbot: 12,
  Grayling: 3,
  Muskie: 32,
  Bass: 8,
  Sucker: 8,
  Chub: 4,
  Smelt: 0.2,
  "Arctic Char": 12,
  Cod: 45,
  Mackerel: 3,
  Halibut: 220,
  Herring: 1,
  Pollock: 18,
  Haddock: 15,
  Ling: 30,
  Saithe: 20,
  Redfish: 10,
  Flatfish: 9,
  "Shark (rare)": 450,
  Tuna: 280,
  Eel: 7,
  Ray: 80,
  Ayu: 0.6,
  Trout: 12,
  Sweetfish: 0.6,
  Goby: 0.3,
  Loach: 0.4,
  Minnow: 0.08,
  Char: 10,
  "Crucian Carp": 3,
  Piranha: 4,
  Arapaima: 200,
  "Peacock Bass": 13,
  "Electric Eel": 20,
  Pacu: 30,
  Arowana: 7,
  Tambaqui: 45,
  Stingray: 140,
  "Knife Fish": 8,
  Oscar: 2,
  Dorado: 25,
  Snakehead: 18,
  "Tiger Fish": 30,
  Payara: 18,
  Barracuda: 45,
  Grouper: 180,
  Snapper: 25,
  "Mahi Mahi": 40,
  Trevally: 80,
  "Coral Trout": 25,
  "Emperor Fish": 20,
  Wrasse: 5,
  Parrotfish: 6,
  Surgeonfish: 3,
  Triggerfish: 5,
  Lionfish: 1,
  "Nile Perch": 200,
  Tilapia: 5,
  Tigerfish: 25,
  Bichir: 10,
  Lungfish: 15,
  Barbel: 12,
  Mullet: 8,
  "Big Carp": 45,
  "Mirror Carp": 35,
  Tench: 7,
  Bream: 7,
  Roach: 1.8,
  Zander: 15,
  Rudd: 2,
  Bleak: 0.12,
  Charr: 12,
  "Cod (rare)": 40,
  "Haddock (rare)": 14,
  Sculpin: 2,
  Stickleback: 0.1,
  Flounder: 7,
};

const uniqueCapable = new Set([
  "Karp",
  "Karp lustrzeń",
  "Szczupak",
  "Sandacz",
  "Sum",
  "Sturgeon",
  "Lake Trout",
  "Northern Pike",
  "Muskie",
  "Cod",
  "Halibut",
  "Shark (rare)",
  "Tuna",
  "Salmon",
  "Arapaima",
  "Peacock Bass",
  "Electric Eel",
  "Arowana",
  "Tambaqui",
  "Stingray",
  "Payara",
  "Barracuda",
  "Grouper",
  "Nile Perch",
  "Big Carp",
  "Mirror Carp",
  "Arctic Char",
]);

const lureTypes = ["natural", "spinner", "crankbait", "jig", "spoon", "popper", "minnow"];
const colors = ["natural", "silver", "gold", "red", "green", "black", "blue", "chartreuse"];
const behaviors = ["calm", "runner", "bruiser", "jumper", "erratic", "cautious"];
const weatherPrefs = ["clear", "cloudy", "rain", "wind", "cold", "warm"];

function hashString(input) {
  let hash = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

function pick(seed, list, offset = 0) {
  return list[(seed + offset) % list.length];
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function createFishSpecies(name, location, index) {
  const seed = hashString(`${location.id}:${name}`);
  const maxWeight = maxWeightOverrides[name] ?? clamp(1 + (seed % 45), 1, 70);
  const tier = location.difficulty;
  const rareName = name.includes("rare");
  const heavyBonus = Math.sqrt(maxWeight) * 14;
  const baseValue = clamp(Math.round(5 + heavyBonus + tier * 8 + (rareName ? 75 : 0)), 5, 500);
  const valuePerKg = clamp(Math.round(1 + Math.log2(maxWeight + 1) * 6 + tier * 1.5), 1, 50);
  const medalChance = clamp(0.035 + tier * 0.006 + (maxWeight > 40 ? 0.018 : 0), 0.03, 0.16);
  const canBeUnique = uniqueCapable.has(name);
  const uniqueChance = canBeUnique
    ? clamp(0.0025 + tier * 0.0013 + (rareName ? 0.005 : 0), 0.002, 0.025)
    : 0;
  const guide = fishGuideOverrides[location.id]?.[name];
  const guidedLures = lureTypesForGuideTerms([...(guide?.best ?? []), ...(guide?.ok ?? [])]);
  const fallbackLures = [
    pick(seed, lureTypes),
    pick(seed, lureTypes, 3),
    maxWeight < 1 ? "natural" : pick(seed, lureTypes, 5),
  ];

  return {
    id: `${location.id}_${index}_${name.toLowerCase().replace(/[^a-z0-9ąćęłńóśźż]+/gi, "_")}`,
    name,
    baseValue,
    valuePerKg,
    maxWeight,
    medalChance,
    uniqueChance,
    canBeUnique,
    behavior: pick(seed, behaviors),
    aggression: clamp(0.2 + ((seed >> 2) % 70) / 100, 0.2, 0.95),
    caution: clamp(0.15 + ((seed >> 5) % 80) / 100, 0.15, 0.95),
    intelligence: clamp(0.2 + ((seed >> 7) % 70) / 100, 0.2, 0.95),
    fearThreshold: clamp(0.22 + ((seed >> 11) % 62) / 100, 0.22, 0.84),
    activeHours: [
      (4 + (seed % 5)) % 24,
      (18 + ((seed >> 4) % 6)) % 24,
    ],
    weatherPreference: pick(seed, weatherPrefs, 2),
    currentPreference: clamp(((seed >> 9) % 100) / 100, 0.08, 0.9),
    preferredLures: [...new Set([...guidedLures, ...fallbackLures])].slice(0, 3),
    preferredColors: [pick(seed, colors, 1), pick(seed, colors, 4)],
    visualHue: (seed % 360),
  };
}

export const LOCATIONS = locationSeeds.map((location) => ({
  ...location,
  fish: fishNamesByLocation[location.id].map((name, index) => createFishSpecies(name, location, index)),
}));

function fallbackGuideForSpecies(species) {
  const best = (species?.preferredLures ?? []).slice(0, 2).map((type) => lureGuideLabels[type] ?? type);
  const ok = (species?.preferredLures ?? []).slice(2, 3).map((type) => lureGuideLabels[type] ?? type);
  return {
    best: best.length ? best : ["naturalne"],
    ok: ok.length ? ok : ["spokojne prowadzenie"],
    bad: species?.maxWeight > 18 ? ["zbyt małe przynęty"] : ["zbyt ciężkie przynęty"],
    note: "",
  };
}

export function getFishGuide(locationId, speciesName) {
  const location = LOCATIONS.find((item) => item.id === locationId);
  const species = location?.fish.find((fish) => fish.name === speciesName);
  const override = fishGuideOverrides[locationId]?.[speciesName];
  return {
    ...fallbackGuideForSpecies(species),
    ...(override ?? {}),
  };
}

export function getLocationGuideNote(locationId) {
  return locationGuideNotes[locationId] ?? "";
}

export const RODS = [
  {
    id: "willow",
    name: "Willow Starter",
    price: 0,
    unlockLevel: 1,
    maxTension: 38,
    control: 0.78,
    castPower: 0.75,
    description: "Lekka wędka startowa",
  },
  {
    id: "riverfox",
    name: "Riverfox M",
    price: 520,
    unlockLevel: 3,
    maxTension: 55,
    control: 0.95,
    castPower: 0.9,
    description: "Szybsza kontrola przynęty",
  },
  {
    id: "carpforce",
    name: "Carpforce 360",
    price: 1280,
    unlockLevel: 6,
    maxTension: 72,
    control: 0.9,
    castPower: 1.08,
    description: "Mocny blank na duże karpie",
  },
  {
    id: "stormline",
    name: "Stormline Ocean",
    price: 3100,
    unlockLevel: 10,
    maxTension: 92,
    control: 0.82,
    castPower: 1.22,
    description: "Ciężka wędka morska",
  },
  {
    id: "apex",
    name: "Apex Titan",
    price: 7600,
    unlockLevel: 15,
    maxTension: 118,
    control: 1.08,
    castPower: 1.38,
    description: "Sprzęt na rekordowe ryby",
  },
];

export const REELS = [
  {
    id: "starter_reel",
    name: "Old Gear 1000",
    price: 0,
    unlockLevel: 1,
    speed: 0.72,
    drag: 35,
    description: "Podstawowy kołowrotek",
  },
  {
    id: "delta_spin",
    name: "Delta Spin 2500",
    price: 450,
    unlockLevel: 3,
    speed: 0.96,
    drag: 48,
    description: "Lepsza praca hamulca",
  },
  {
    id: "deep_crank",
    name: "Deep Crank 4000",
    price: 1200,
    unlockLevel: 6,
    speed: 1.08,
    drag: 64,
    description: "Stabilny hol głębokich ryb",
  },
  {
    id: "bluewater",
    name: "Bluewater 7000",
    price: 3400,
    unlockLevel: 10,
    speed: 1.2,
    drag: 86,
    description: "Morski hamulec",
  },
  {
    id: "titan_drag",
    name: "Titan Drag 9000",
    price: 8200,
    unlockLevel: 16,
    speed: 1.34,
    drag: 112,
    description: "Najwyższa wytrzymałość",
  },
];

export const LINES = [
  {
    id: "nylon_3",
    name: "Nylon 3 kg",
    price: 0,
    unlockLevel: 1,
    strength: 30,
    friction: 0.95,
    snagResist: 0.45,
    description: "Cicha, lekka żyłka",
  },
  {
    id: "fluoro_6",
    name: "Fluoro 6 kg",
    price: 240,
    unlockLevel: 2,
    strength: 44,
    friction: 0.9,
    snagResist: 0.58,
    description: "Dobra widoczność brań",
  },
  {
    id: "braid_10",
    name: "Braid 10 kg",
    price: 780,
    unlockLevel: 5,
    strength: 62,
    friction: 1.05,
    snagResist: 0.64,
    description: "Mocna plecionka rzeczna",
  },
  {
    id: "braid_18",
    name: "Braid 18 kg",
    price: 1750,
    unlockLevel: 9,
    strength: 82,
    friction: 1.12,
    snagResist: 0.75,
    description: "Duże ryby i szybki nurt",
  },
  {
    id: "kevlar_30",
    name: "Kevlar 30 kg",
    price: 4800,
    unlockLevel: 14,
    strength: 112,
    friction: 1.18,
    snagResist: 0.88,
    description: "Sprzęt na rekordy",
  },
];

export const LURES = [
  {
    id: "bread",
    name: "Bread Ball",
    price: 0,
    unlockLevel: 1,
    type: "natural",
    color: "natural",
    mass: 0.38,
    drag: 0.82,
    sinkRate: 0.16,
    noise: 0.08,
    description: "Mała naturalna przynęta",
  },
  {
    id: "red_worm",
    name: "Red Worm",
    price: 0,
    unlockLevel: 1,
    type: "natural",
    color: "red",
    mass: 0.34,
    drag: 0.72,
    sinkRate: 0.18,
    noise: 0.1,
    description: "Uniwersalny robak",
  },
  {
    id: "corn_kernel",
    name: "Corn Kernel",
    price: 35,
    unlockLevel: 1,
    type: "natural",
    color: "gold",
    mass: 0.3,
    drag: 0.7,
    sinkRate: 0.12,
    noise: 0.06,
    description: "Kukurydza na karpie, amury i spokojne ryby",
  },
  {
    id: "meat_strip",
    name: "Meat Strip",
    price: 120,
    unlockLevel: 2,
    type: "natural",
    color: "red",
    mass: 0.48,
    drag: 0.78,
    sinkRate: 0.2,
    noise: 0.14,
    description: "Mięso na sumy, drapieżniki i ryby rzeczne",
  },
  {
    id: "plant_mix",
    name: "Plant Mix",
    price: 140,
    unlockLevel: 2,
    type: "natural",
    color: "green",
    mass: 0.36,
    drag: 0.76,
    sinkRate: 0.13,
    noise: 0.05,
    description: "Roślinna przynęta na amury i tilapie",
  },
  {
    id: "silver_spinner",
    name: "Silver Spinner",
    price: 90,
    unlockLevel: 1,
    type: "spinner",
    color: "silver",
    mass: 0.55,
    drag: 1.08,
    sinkRate: 0.22,
    noise: 0.34,
    description: "Błysk i wibracja",
  },
  {
    id: "soft_plastic",
    name: "Soft Plastic",
    price: 170,
    unlockLevel: 2,
    type: "jig",
    color: "green",
    mass: 0.6,
    drag: 0.92,
    sinkRate: 0.28,
    noise: 0.22,
    description: "Guma na okonie, sandacze i bassy",
  },
  {
    id: "small_wobbler",
    name: "Small Wobbler",
    price: 190,
    unlockLevel: 2,
    type: "crankbait",
    color: "blue",
    mass: 0.54,
    drag: 1.18,
    sinkRate: 0.24,
    noise: 0.32,
    description: "Wobler do aktywnego prowadzenia",
  },
  {
    id: "green_crank",
    name: "Green Crank",
    price: 220,
    unlockLevel: 3,
    type: "crankbait",
    color: "green",
    mass: 0.68,
    drag: 1.28,
    sinkRate: 0.3,
    noise: 0.42,
    description: "Praca na średniej głębokości",
  },
  {
    id: "gold_spoon",
    name: "Gold Spoon",
    price: 340,
    unlockLevel: 4,
    type: "spoon",
    color: "gold",
    mass: 0.8,
    drag: 1.18,
    sinkRate: 0.36,
    noise: 0.3,
    description: "Ciężka wahadłówka",
  },
  {
    id: "black_jig",
    name: "Black Jig",
    price: 620,
    unlockLevel: 6,
    type: "jig",
    color: "black",
    mass: 1.1,
    drag: 0.88,
    sinkRate: 0.58,
    noise: 0.24,
    description: "Szybki opad",
  },
  {
    id: "blue_minnow",
    name: "Blue Minnow",
    price: 980,
    unlockLevel: 9,
    type: "minnow",
    color: "blue",
    mass: 0.92,
    drag: 1.04,
    sinkRate: 0.33,
    noise: 0.38,
    description: "Naturalny ruch rybki",
  },
  {
    id: "bait_fish",
    name: "Bait Fish",
    price: 1180,
    unlockLevel: 10,
    type: "minnow",
    color: "silver",
    mass: 1.02,
    drag: 1.08,
    sinkRate: 0.36,
    noise: 0.34,
    description: "Mała ryba na duże drapieżniki",
  },
  {
    id: "reef_popper",
    name: "Reef Popper",
    price: 1600,
    unlockLevel: 12,
    type: "popper",
    color: "chartreuse",
    mass: 1.28,
    drag: 1.5,
    sinkRate: -0.06,
    noise: 0.72,
    description: "Głośna przynęta powierzchniowa",
  },
];

export const BACKPACKS = [
  {
    id: "basic",
    name: "Basic",
    price: 0,
    unlockLevel: 1,
    rodSlots: 1,
    keepnetKg: 25,
    description: "1 wędka",
  },
  {
    id: "medium",
    name: "Medium",
    price: 900,
    unlockLevel: 4,
    rodSlots: 2,
    keepnetKg: 55,
    description: "2 wędki",
  },
  {
    id: "advanced",
    name: "Advanced",
    price: 2600,
    unlockLevel: 8,
    rodSlots: 3,
    keepnetKg: 100,
    description: "3 wędki",
  },
  {
    id: "pro",
    name: "Pro",
    price: 6800,
    unlockLevel: 13,
    rodSlots: 4,
    keepnetKg: 180,
    description: "4 wędki",
  },
];

export const ADDONS = [
  {
    id: "bite_alarm",
    name: "Bite Alarm",
    price: 400,
    unlockLevel: 2,
    detection: 0.08,
    description: "Lepsza sygnalizacja brań",
  },
  {
    id: "polar_glasses",
    name: "Polar Glasses",
    price: 750,
    unlockLevel: 5,
    detection: 0.12,
    control: 0.05,
    description: "Czytelniejsza praca przynęty",
  },
  {
    id: "sonar_mini",
    name: "Mini Sonar",
    price: 2100,
    unlockLevel: 9,
    detection: 0.2,
    luck: 0.04,
    description: "Większa szansa na duże ryby",
  },
];

export const LEGENDARIES = {
  poland_small_lake: {
    id: "white_king_carp",
    name: "Biały Król",
    species: "Karp",
    minLevel: 4,
    value: 2200,
    behavior: "bruiser",
    color: "#f6f0d2",
  },
  usa_river_delta: {
    id: "delta_old_gar",
    name: "Old Needle",
    species: "Gar",
    minLevel: 5,
    value: 3400,
    behavior: "runner",
    color: "#b9e071",
  },
  canada_deep_lake: {
    id: "cold_crown_trout",
    name: "Cold Crown",
    species: "Lake Trout",
    minLevel: 8,
    value: 4700,
    behavior: "cautious",
    color: "#bddcff",
  },
  norway_ocean_coast: {
    id: "fjord_shadow_halibut",
    name: "Fjord Shadow",
    species: "Halibut",
    minLevel: 11,
    value: 8800,
    behavior: "bruiser",
    color: "#9daab0",
  },
  japan_mountain_river: {
    id: "silver_monk_char",
    name: "Silver Monk",
    species: "Char",
    minLevel: 9,
    value: 4100,
    behavior: "erratic",
    color: "#d7f8ff",
  },
  brazil_amazon_river: {
    id: "red_moon_arapaima",
    name: "Red Moon",
    species: "Arapaima",
    minLevel: 14,
    value: 12500,
    behavior: "runner",
    color: "#ff7e69",
  },
  australia_coral_sea: {
    id: "reef_titan_grouper",
    name: "Reef Titan",
    species: "Grouper",
    minLevel: 17,
    value: 14800,
    behavior: "bruiser",
    color: "#ffc06a",
  },
  egypt_nile_river: {
    id: "nile_emperor",
    name: "Nile Emperor",
    species: "Nile Perch",
    minLevel: 12,
    value: 9700,
    behavior: "runner",
    color: "#f0d064",
  },
  france_carp_lake: {
    id: "mirror_duchess",
    name: "Mirror Duchess",
    species: "Mirror Carp",
    minLevel: 10,
    value: 7600,
    behavior: "cautious",
    color: "#ffe0a6",
  },
  iceland_ice_river: {
    id: "aurora_char",
    name: "Aurora Char",
    species: "Arctic Char",
    minLevel: 13,
    value: 9000,
    behavior: "jumper",
    color: "#8ff9ef",
  },
};

export const SHOP_CATEGORIES = [
  { id: "rods", label: "Wędki", items: RODS, ownedKey: "rods", equippedKey: "rod" },
  { id: "reels", label: "Kołowrotki", items: REELS, ownedKey: "reels", equippedKey: "reel" },
  { id: "lines", label: "Żyłki", items: LINES, ownedKey: "lines", equippedKey: "line" },
  { id: "lures", label: "Przynęty", items: LURES, ownedKey: "lures", equippedKey: "lure" },
  { id: "backpacks", label: "Plecaki", items: BACKPACKS, ownedKey: "backpacks", equippedKey: "backpack" },
  { id: "addons", label: "Dodatki", items: ADDONS, ownedKey: "addons", equippedKey: null },
];

export function findById(list, id) {
  return list.find((item) => item.id === id);
}

export function getLocation(id) {
  return LOCATIONS.find((location) => location.id === id);
}

export function getEquipmentById(kind, id) {
  const map = {
    rod: RODS,
    reel: REELS,
    line: LINES,
    lure: LURES,
    backpack: BACKPACKS,
  };
  return findById(map[kind] ?? [], id);
}

export function getSpecies(locationId, speciesName) {
  const location = getLocation(locationId);
  return location?.fish.find((fish) => fish.name === speciesName);
}
